import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '../components/Header/Header'
import About from '../components/About/About'

export default function Home() {
  return (
    <>
      <Head>
        <title>Landing Common</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <About/>
      </main>
    </>
  )
}
